[package]
name = "basic_concepts"
version = "0.1.0"
authors = ["Michiel Schoofs <michiel.schoofs@student.hogent.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
